### ISSUE TITLE
Not showing in Curseforge

### ISSUE THREAD

**Issue by Frurox** [N6REJ/AdiBags_Bears_Hearthstones#1]
Not showing in Curseforge [adibags_bears_hearthstones](https://www.curseforge.com/wow/addons/adibags_bears_hearthstones)
<img width="737" alt="image" src="https://user-images.githubusercontent.com/47403751/202821806-a18cfb7c-4e40-41ab-8fca-28d0e819f1cb.png">

**Comment by N6REJ** [comment]
Thats because they take a few days to start a new addon.  You can use wago to install it via wowup or manually.  Then when curseforge has updates it will still update it.
